name: get_csv_of_group_members
channels: 
  - anaconda-fusion
  - defaults
  - conda-forge
dependencies: 
  - jupyter
  - pandas
  - pip
  - pip: 
      - canvasapi
      - python-dotenv
      - getpass
      - datetime
      - termcolor
